backend:
  name: github
  repo: simple-question/simple-question.org
  branch: master

publish_mode: editorial_workflow

media_folder: "uploads"

collections:
  - name: "Actualités"
    label: "Actualités"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Catégorie", name: "category", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Texte", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "La Charte"
        name: "charte"
        file: "charte.md"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Texte", name: "body", widget: "markdown"}
      - label: "Les Questions"
        name: "questions"
        file: "_data/questions.yml"
        fields:
          - label: "Questions"
            name: "questions"
            widget: "list"
            field: {label: "Question", widget: string}
      - label: "L'Equipe"
        name: "people"
        file: "_data/team.yml"
        fields:
          - label: Members
            name: members
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Bio, name: bio, widget: string}
              - {label: Photo, name: image, widget: image}
